spring.application.name=primavera


# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/otec_primavera
spring.datasource.username=root
spring.datasource.password=oi55oi17
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración del servidor
server.port=8080

# Configuración Thymeleaf
spring.thymeleaf.cache=false